# Generated by Django 6.0.4 on 2026-05-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BORROWED', 'Borrowed'), ('MISSING', 'Missing'), ('RETURNED', 'Returned'), ('ACTIVE', 'Active'), ('LOST', 'Lost')], default='AVAILABLE', max_length=15),
        ),
    ]
