# Generated by Django 6.0.4 on 2026-04-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved by Student/Teacher'), ('active', 'Borrowed (Active)'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
