import { useState } from 'react';

function Reports({ books, transactions, user }) {
  const [reportType, setReportType] = useState('inventory');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  const filteredTransactions = transactions.filter(tx => {
    if (!startDate && !endDate) return true;
    const txDate = new Date(tx.reservation_date || tx.due_date);
    const start = startDate ? new Date(startDate) : new Date('2000-01-01');
    const end = endDate ? new Date(endDate) : new Date('2100-01-01');
    return txDate >= start && txDate <= end;
  });

  const overdueBooks = transactions.filter(tx => {
    if (tx.status !== 'ACTIVE') return false;
    const diffDays = Math.ceil((new Date(tx.due_date).setHours(0,0,0,0) - new Date().setHours(0,0,0,0)) / (1000 * 60 * 60 * 24));
    return diffDays < 0;
  });

  const lostBooks = transactions.filter(tx => tx.status === 'LOST');

  const handlePrint = (e) => {
    e.preventDefault();
    const iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    document.body.appendChild(iframe);

    let tableHeaders = '';
    let tableRows = '';
    let reportTitle = '';
    let reportMeta = '';

    if (reportType === 'inventory') {
      reportTitle = 'Library Inventory Status Report';
      reportMeta = `Total Titles: ${books.length}`;
      tableHeaders = `<tr><th>ISBN</th><th>Title</th><th>Author</th><th>Category</th><th>Total Copies</th><th>Available</th></tr>`;
      tableRows = books.map(b => `
        <tr>
          <td>${b.isbn || 'N/A'}</td>
          <td><strong>${b.title}</strong></td>
          <td>${b.author}</td>
          <td>${b.category}</td>
          <td>${b.copies?.length || 0}</td>
          <td>${b.active_copies_count ?? (b.copies?.length || 0)}</td>
        </tr>
      `).join('');
    } else if (reportType === 'circulation') {
      reportTitle = 'Circulation & Borrowing Log';
      reportMeta = `Date Filter: ${startDate || 'All Time'} to ${endDate || 'Present'} <br/> Total Records: ${filteredTransactions.length}`;
      tableHeaders = `<tr><th>Borrower ID</th><th>Book Title</th><th>Due Date</th><th>Return Date</th><th>Status</th></tr>`;
      tableRows = filteredTransactions.map(tx => `
        <tr>
          <td>${tx.user?.username || tx.member_id || 'Unknown'}</td>
          <td><strong>${tx.book_title}</strong></td>
          <td>${new Date(tx.due_date).toLocaleDateString()}</td>
          <td>${tx.return_date ? new Date(tx.return_date).toLocaleDateString() : '-'}</td>
          <td><strong>${tx.status}</strong></td>
        </tr>
      `).join('');
    } else if (reportType === 'attention') {
      reportTitle = 'Action Required: Overdue & Lost Books';
      reportMeta = `Total Overdue: ${overdueBooks.length} | Total Lost: ${lostBooks.length}`;
      tableHeaders = `<tr><th>Borrower ID</th><th>Book Title</th><th>Due Date</th><th>Current Status</th></tr>`;
      tableRows = [...overdueBooks, ...lostBooks].map(tx => `
        <tr>
          <td>${tx.user?.username || tx.member_id || 'Unknown'}</td>
          <td><strong>${tx.book_title}</strong></td>
          <td>${new Date(tx.due_date).toLocaleDateString()}</td>
          <td style="color: red; font-weight: bold;">${tx.status === 'LOST' ? 'LOST' : 'OVERDUE'}</td>
        </tr>
      `).join('');
    }

    iframe.contentDocument.write(`
      <html>
        <head>
          <title>LibTrack - ${reportTitle}</title>
          <style>
            body { font-family: 'Times New Roman', Times, serif; padding: 40px; color: #333; line-height: 1.4; }
            .header { text-align: center; border-bottom: 2px solid #14291c; padding-bottom: 15px; margin-bottom: 20px; }
            .header h1 { margin: 0; color: #14291c; font-size: 22px; text-transform: uppercase; }
            .header h2 { margin: 5px 0; color: #555; font-size: 16px; }
            .meta { font-size: 12px; color: #333; margin-bottom: 20px; display: flex; justify-content: space-between; }
            table { border-collapse: collapse; width: 100%; font-size: 11px; font-family: Arial, sans-serif; }
            th, td { border: 1px solid #aaa; padding: 8px; text-align: left; }
            th { background-color: #f4f6f5; color: #14291c; font-weight: bold; text-transform: uppercase; }
            tr:nth-child(even) { background-color: #f9f9f9; }
            .footer { margin-top: 40px; text-align: right; font-size: 12px; }
            @media print { body { padding: 0; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Jose Panganiban National High School (JPNHS)</h1>
            <h2>${reportTitle}</h2>
          </div>
          <div class="meta">
            <div>
              <strong>Generated By:</strong> ${user?.first_name} ${user?.last_name} (${user?.role})<br/>
              <strong>Date Generated:</strong> ${new Date().toLocaleString()}
            </div>
            <div style="text-align: right;">
              ${reportMeta}
            </div>
          </div>
          <table>
            <thead>${tableHeaders}</thead>
            <tbody>${tableRows.length > 0 ? tableRows : '<tr><td colspan="6" style="text-align: center;">No records found.</td></tr>'}</tbody>
          </table>
          <div class="footer">
            <p>Certified Correct:</p>
            <br/><br/>
            <p>___________________________<br/><strong>${user?.first_name} ${user?.last_name}</strong><br/>School Librarian</p>
          </div>
        </body>
      </html>
    `);
    iframe.contentDocument.close();

    setTimeout(() => {
      iframe.contentWindow.focus();
      iframe.contentWindow.print();
      setTimeout(() => document.body.removeChild(iframe), 1000);
    }, 250);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 animate-in fade-in slide-in-from-bottom-4 duration-500 max-w-7xl mx-auto">

      <div className="lg:col-span-1 space-y-6">
        <div className="bg-white rounded-2xl shadow-sm border border-stone-100 overflow-hidden">
          <div className="bg-[#1a3626] p-4 border-b border-emerald-800">
            <h3 className="font-serif font-bold text-lg text-white">Report Settings</h3>
          </div>
          <div className="p-6 space-y-6">
            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Report Type</label>
              <select value={reportType} onChange={(e) => setReportType(e.target.value)} className="w-full p-3 bg-stone-50 border border-stone-200 rounded-lg outline-none focus:ring-2 focus:ring-[#1a3626] text-sm font-bold text-slate-700">
                <option value="inventory">📚 Inventory Status</option>
                <option value="circulation">🔄 Circulation / Logs</option>
                <option value="attention">⚠️ Overdue / Lost Books</option>
              </select>
            </div>

            {reportType === 'circulation' && (
              <div className="space-y-4 animate-in fade-in duration-300">
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Start Date</label>
                  <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-full p-3 bg-stone-50 border border-stone-200 rounded-lg outline-none text-sm text-slate-700" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">End Date</label>
                  <input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-full p-3 bg-stone-50 border border-stone-200 rounded-lg outline-none text-sm text-slate-700" />
                </div>
              </div>
            )}

            <div className="pt-4 border-t border-stone-100">
              <button onClick={handlePrint} className="w-full bg-[#1a3626] text-white px-4 py-3 rounded-xl font-bold shadow-md hover:bg-[#0f2117] transition-all flex items-center justify-center gap-2">
                <span>🖨️</span> Generate & Print
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="lg:col-span-3">
        <div className="bg-white rounded-2xl shadow-sm border border-stone-100 overflow-hidden h-full flex flex-col">
          <div className="p-6 border-b border-stone-100 bg-stone-50 flex justify-between items-center">
            <h3 className="font-serif font-bold text-lg text-slate-900">
              {reportType === 'inventory' && 'Preview: Inventory Status'}
              {reportType === 'circulation' && 'Preview: Circulation Logs'}
              {reportType === 'attention' && 'Preview: Overdue & Lost'}
            </h3>
            <span className="text-xs font-bold text-slate-400 bg-white px-3 py-1 rounded-full border border-stone-200">
              {reportType === 'inventory' && `${books.length} Books`}
              {reportType === 'circulation' && `${filteredTransactions.length} Records`}
              {reportType === 'attention' && `${overdueBooks.length + lostBooks.length} Action Items`}
            </span>
          </div>

          <div className="overflow-x-auto flex-1 p-6">
            {reportType === 'inventory' && (
              <table className="w-full text-left text-sm border-collapse">
                <thead><tr className="text-xs text-slate-500 uppercase border-b border-stone-200"><th className="pb-3">Title</th><th className="pb-3">Author</th><th className="pb-3">Copies</th></tr></thead>
                <tbody className="divide-y divide-stone-100">
                  {books.slice(0, 10).map(b => (
                    <tr key={b.id}>
                      <td className="py-3 font-bold text-slate-800">{b.title}</td><td className="py-3 text-slate-600">{b.author}</td>
                      <td className="py-3 font-bold text-emerald-700">{b.active_copies_count ?? (b.copies?.length || 0)}</td>
                    </tr>
                  ))}
                  {books.length > 10 && <tr><td colSpan="3" className="text-center py-4 text-xs text-slate-400 font-bold italic">...and {books.length - 10} more records (visible on print)</td></tr>}
                </tbody>
              </table>
            )}

            {reportType === 'circulation' && (
              <table className="w-full text-left text-sm border-collapse">
                <thead><tr className="text-xs text-slate-500 uppercase border-b border-stone-200"><th className="pb-3">Borrower</th><th className="pb-3">Book</th><th className="pb-3">Status</th></tr></thead>
                <tbody className="divide-y divide-stone-100">
                  {filteredTransactions.slice(0, 10).map(tx => (
                    <tr key={tx.id}>
                      <td className="py-3 font-bold text-slate-800">{tx.user?.username || tx.member_id}</td><td className="py-3 text-slate-600 truncate max-w-40">{tx.book_title}</td>
                      <td className="py-3"><span className="text-[10px] font-bold px-2 py-1 bg-stone-100 rounded-md border border-stone-200">{tx.status}</span></td>
                    </tr>
                  ))}
                  {filteredTransactions.length === 0 && <tr><td colSpan="3" className="text-center py-8 text-slate-500">No transactions match these dates.</td></tr>}
                  {filteredTransactions.length > 10 && <tr><td colSpan="3" className="text-center py-4 text-xs text-slate-400 font-bold italic">...and {filteredTransactions.length - 10} more records (visible on print)</td></tr>}
                </tbody>
              </table>
            )}

            {reportType === 'attention' && (
              <table className="w-full text-left text-sm border-collapse">
                <thead><tr className="text-xs text-slate-500 uppercase border-b border-stone-200"><th className="pb-3">Borrower</th><th className="pb-3">Book</th><th className="pb-3">Due Date</th><th className="pb-3">Status</th></tr></thead>
                <tbody className="divide-y divide-stone-100">
                  {[...overdueBooks, ...lostBooks].map(tx => (
                    <tr key={tx.id}>
                      <td className="py-3 font-bold text-slate-800">{tx.user?.username || tx.member_id}</td><td className="py-3 text-slate-600">{tx.book_title}</td>
                      <td className="py-3 text-slate-600">{new Date(tx.due_date).toLocaleDateString()}</td>
                      <td className="py-3 font-bold text-red-600">{tx.status === 'LOST' ? 'LOST' : 'OVERDUE'}</td>
                    </tr>
                  ))}
                  {overdueBooks.length === 0 && lostBooks.length === 0 && <tr><td colSpan="4" className="text-center py-8 text-slate-500">No overdue or lost books!</td></tr>}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>

    </div>
  );
}

export default Reports;