# Generated by Django 6.0.4 on 2026-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_image', models.ImageField(upload_to='logbook_scans/')),
                ('extracted_text_json', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processed', 'Processed Successfully'), ('error', 'Processing Error')], default='pending', max_length=20)),
            ],
        ),
    ]
