# Generated by Django 6.0.4 on 2026-04-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved (Pending Pickup)'), ('borrowed', 'Currently Borrowed'), ('missing', 'Missing'), ('destroyed', 'Destroyed'), ('outdated', 'Outdated/Archived'), ('new_arrival', 'New Arrival')], default='new_arrival', max_length=20),
        ),
    ]
