# Generated by Django 6.0.4 on 2026-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=15),
        ),
    ]
