# Generated by Django 6.0.4 on 2026-05-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expected_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
