# Generated by Django 6.0.4 on 2026-05-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_expected_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled'), ('RESOLVED', 'Resolved')], default='RESERVED', max_length=15),
        ),
    ]
