# Generated by Django 6.0.4 on 2026-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
