# Generated by Django 6.0.4 on 2026-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_requires_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('LIBRARIAN', 'Librarian'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='ADMIN', max_length=15),
        ),
    ]
